// <auto-generated/>
// Stub — run the following to populate with real data:
//   dotnet run --project tools/postal/Postal.Builder -- codegen <rall1.dbf> <this-file> --nested
// Until then, PostalRulesEngine falls back to PostalData.Rules for all lookups.

#nullable enable

namespace TaiwanUtilities.Internals;

internal static class PostalLookup
{
    internal static bool TryFind(string? city, string? district, string? road, out PostalRuleSet ruleSet)
    {
        ruleSet = default;
        return false;
    }
}
