// <auto-generated/>
// SPDX-License-Identifier: MIT
// Postal code data from Chunghwa Post under OGDL-Taiwan-1.0
// This file is generated by: dotnet run --project tools/postal/Postal.Builder -- codegen [dbf] [output]
// DO NOT EDIT MANUALLY.

#nullable enable

namespace TaiwanUtilities.Internals;

using System;
using System.Collections.Generic;

#if NET8_0_OR_GREATER
using System.Collections.Frozen;
#endif

internal static class PostalData
{
    internal static readonly string GeneratedDate = "placeholder";
    internal static readonly int RecordCount = 0;

    internal static readonly string[] ZipCodePool = Array.Empty<string>();
    internal static readonly string[] Departments = new[] { string.Empty };
    internal static readonly string[] Offices = new[] { string.Empty };
    internal static readonly string[] Scopes = new[] { string.Empty };
    internal static readonly HashSet<string> SpecialRoadNames = new HashSet<string>(StringComparer.Ordinal);

#if NET8_0_OR_GREATER
    internal static readonly FrozenDictionary<string, PostalRuleSet> Rules =
        FrozenDictionary<string, PostalRuleSet>.Empty;
#else
    internal static readonly Dictionary<string, PostalRuleSet> Rules =
        new Dictionary<string, PostalRuleSet>(StringComparer.Ordinal);
#endif
}
